GET http://localhost:3500/users HTTP/1.1
content-type: application/json

####


POST http://localhost:3500/users HTTP/1.1
content-type: application/json

{
    "username": "sito",
    "password": "listenM0re",
    "roles": ["manager"] 
}

###

PATCH http://localhost:3500/users HTTP/1.1
content-type: application/json

{
    "id": "640dd815c2f230081d2ca422",
    "username": "Ojyji",
    
    "roles": ["Employee"] ,
    "active": false
}
###

DELETE http://localhost:3500/users HTTP/1.1
content-type: application/json

{
    "id" : "640dd92fc2f230081d2ca427"
}

###

GET http://localhost:3500/notes HTTP/1.1
content-type: application/json


###

POST http://localhost:3500/notes HTTP/1.1
content-type: application/json

{
    "user" : "640e40aac4828accc12a7293",
    "title": "girate",
    "text" : "working Hands of God"
}

###
PATCH http://localhost:3500/notes HTTP/1.1
content-type: application/json

{
    "user" : "640e40aac4828accc12a7293",
    "title": "girate",
    "text" : "working Hands of God",
    "completed": true,
    "id": "642d428fc2ef511bf9659e29"

}

###
DELETE http://localhost:3500/notes HTTP/1.1
content-type: application/json

{
    "id": "642d468c23feffbf9fa48600"
}

###

POST http://localhost:3500/auth HTTP/1.1
content-type: application/json

{
    "username": "sito",
    "password": "listenM0re"
}
####
GET http://localhost:3500/auth/refresh HTTP/1.1
content-type: application/json

{
    "username": "sito",
    "password": "listenM0re"
}
###
POST  http://localhost:3500/auth/logout HTTP/1.1
content-type: application/json

{
    "username": "sito",
    "password": "listenM0re"
}